## T1 syllabus
- Unit 1 = 13 marks
- Unit 2 = 8  marks
- Unit 3 = 4  marks

## Pandas Library
- panal data system
- used for data manipulation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Create Series
- 1D pandas datastructure

In [ ]:
# using list
a=pd.Series([1,2,3,4,9,10])
print(a)
print(type(a))

In [ ]:
# using tuple
a=pd.Series((1,2,3,4,9,10))
print(a)
print(type(a))

In [ ]:
# using dictioary
a=pd.Series({
    'a':'Python',
    'b':'java'
})
print(a)
print(type(a))

In [ ]:
# using range
a=pd.Series(range(1,6))
print(a)
print(type(a))

## DataFrame
- A 2D pandas data structure
- includes rows and columns
- a group of multiple dataframes is called panel
- a group of multiple series is called dataframe

In [ ]:
a=pd.DataFrame({
    'name':['A','B','C'],
    'marks':[80,90,100]
})
print(a)
print(type(a))

In [ ]:
# using list of lists

a=pd.DataFrame([['A',80],['B',90],['C',100]],columns=['name','marks'])
print(a)
print(type(a))

In [ ]:
# using list of dictionaries
pd.DataFrame([
    {'name':'A','marks':80},
    {'name':'B','marks':90},
    {'name':'C','marks':100}
])
# print(a)
# print(type(a))

## Import and load CSV

In [ ]:
df=pd.read_csv('p1.csv')
df

## Exercise

In [2]:
df=pd.read_csv('students.csv')
df

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

## set index and reset index
- case sensitive
- old dataframe is not changed(if inplace is not True)

In [3]:
df.set_index('StudentID')

             Name Department   Age  Marks  Attendance       City
StudentID
1            Amit         CS  20.0   85.0        92.0  Ahmedabad
2            Neha         IT  21.0   78.0        88.0      Surat
3            Ravi         CS  19.0   90.0        95.0  Ahmedabad
4            Sara         EC  22.0   66.0        70.0   Vadodara
5            John         IT  20.0  120.0        85.0     Rajkot
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad
7            Riya         IT  20.0   76.0         NaN      Surat
8           Arjun         CS  22.0    NaN        93.0  Ahmedabad
9           Pooja         EC  19.0   69.0        75.0   Vadodara
10          Mehul         CS  21.0   92.0        97.0  Ahmedabad
11          Anita         IT  20.0   74.0        80.0      Surat
12          Rohan         CS  22.0   84.0        91.0  Ahmedabad
13          Deepa         EC   NaN   67.0        72.0   Vadodara
14          Sneha         IT  20.0   79.0        86.0      Surat
15          Kunal         CS  23.0   91.0        96.0  Ahmedabad
16          Payal         EC  19.0   65.0        68.0   Vadodara
17         Nikhil         IT  22.0   83.0        89.0      Surat
18         Simran         CS  21.0   87.0        94.0  Ahmedabad
19          Tarun         CS  20.0   77.0        84.0     Rajkot
20           Isha         IT   NaN   30.0        87.0      Surat
2            Neha         IT  21.0   78.0        88.0      Surat
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [4]:
df # old dataframe is not changed

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [5]:
df.set_index('StudentID',inplace=True) # old dataframe is changed
# do not run it twice

In [6]:
df

             Name Department   Age  Marks  Attendance       City
StudentID
1            Amit         CS  20.0   85.0        92.0  Ahmedabad
2            Neha         IT  21.0   78.0        88.0      Surat
3            Ravi         CS  19.0   90.0        95.0  Ahmedabad
4            Sara         EC  22.0   66.0        70.0   Vadodara
5            John         IT  20.0  120.0        85.0     Rajkot
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad
7            Riya         IT  20.0   76.0         NaN      Surat
8           Arjun         CS  22.0    NaN        93.0  Ahmedabad
9           Pooja         EC  19.0   69.0        75.0   Vadodara
10          Mehul         CS  21.0   92.0        97.0  Ahmedabad
11          Anita         IT  20.0   74.0        80.0      Surat
12          Rohan         CS  22.0   84.0        91.0  Ahmedabad
13          Deepa         EC   NaN   67.0        72.0   Vadodara
14          Sneha         IT  20.0   79.0        86.0      Surat
15          Kunal         CS  23.0   91.0        96.0  Ahmedabad
16          Payal         EC  19.0   65.0        68.0   Vadodara
17         Nikhil         IT  22.0   83.0        89.0      Surat
18         Simran         CS  21.0   87.0        94.0  Ahmedabad
19          Tarun         CS  20.0   77.0        84.0     Rajkot
20           Isha         IT   NaN   30.0        87.0      Surat
2            Neha         IT  21.0   78.0        88.0      Surat
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [7]:
df.reset_index()

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [8]:
df # old dataframe is not changed

             Name Department   Age  Marks  Attendance       City
StudentID
1            Amit         CS  20.0   85.0        92.0  Ahmedabad
2            Neha         IT  21.0   78.0        88.0      Surat
3            Ravi         CS  19.0   90.0        95.0  Ahmedabad
4            Sara         EC  22.0   66.0        70.0   Vadodara
5            John         IT  20.0  120.0        85.0     Rajkot
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad
7            Riya         IT  20.0   76.0         NaN      Surat
8           Arjun         CS  22.0    NaN        93.0  Ahmedabad
9           Pooja         EC  19.0   69.0        75.0   Vadodara
10          Mehul         CS  21.0   92.0        97.0  Ahmedabad
11          Anita         IT  20.0   74.0        80.0      Surat
12          Rohan         CS  22.0   84.0        91.0  Ahmedabad
13          Deepa         EC   NaN   67.0        72.0   Vadodara
14          Sneha         IT  20.0   79.0        86.0      Surat
15          Kunal         CS  23.0   91.0        96.0  Ahmedabad
16          Payal         EC  19.0   65.0        68.0   Vadodara
17         Nikhil         IT  22.0   83.0        89.0      Surat
18         Simran         CS  21.0   87.0        94.0  Ahmedabad
19          Tarun         CS  20.0   77.0        84.0     Rajkot
20           Isha         IT   NaN   30.0        87.0      Surat
2            Neha         IT  21.0   78.0        88.0      Surat
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [9]:
df.reset_index(inplace=True) # old dataframe is changed

In [10]:
df

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

## DataFrame Attributes

In [ ]:
print(df.shape)
print(df.size)
print(df.ndim)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.values)

## Indexing and Slicing (Accessing elements)

In [18]:
data={
    'name':['A','B','C','D','E'],
    'marks':[85,90,95,np.nan,99],
    'bonus':[1,2,3,4,7],
    'city':['ahm','raj','ahm','ahm','raj']
}
df=pd.DataFrame(data)
df

  name  marks  bonus city
0    A   85.0      1  ahm
1    B   90.0      2  raj
2    C   95.0      3  ahm
3    D    NaN      4  ahm
4    E   99.0      7  raj

## loc method
- label based method for slicing and indexing

In [19]:
df.loc[0]

name       A
marks     85
bonus      1
city     ahm
Name: 0, dtype: object

In [20]:
df.loc[0,'marks']

85.0

## Assign values

In [22]:
df.loc[0,'marks']=200

In [23]:
df

  name  marks  bonus city
0    A  200.0      1  ahm
1    B   90.0      2  raj
2    C   95.0      3  ahm
3    D    NaN      4  ahm
4    E   99.0      7  raj

## Slicing

In [25]:
df.loc[0:2,['marks','city']]  # last index is included here

   marks city
0  200.0  ahm
1   90.0  raj
2   95.0  ahm

## Add column

In [30]:
df.loc[:,'total']=df['marks']+df['bonus']

In [31]:
df

  name  marks  bonus city  total
0    A  200.0      1  ahm  201.0
1    B   90.0      2  raj   92.0
2    C   95.0      3  ahm   98.0
3    D    NaN      4  ahm    NaN
4    E   99.0      7  raj  106.0

## Add row

In [42]:
df.loc['python']=['F',80,10,'anand']

ValueError: Must have equal len keys and value when setting with an iterable

In [ ]:
df.loc['python']=['F',80,10,'anand',90.92]

In [40]:
df

       name  marks  bonus   city   total
0         A  200.0      1    ahm  201.00
1         B   90.0      2    raj   92.00
2         C   95.0      3    ahm   98.00
3         D    NaN      4    ahm     NaN
4         E   99.0      7    raj  106.00
6         F   80.0     10  anand   90.92
5         F   80.0     10  anand   90.92
500       F   80.0     10  anand   90.92
python    F   80.0     10  anand   90.92

In [41]:
df.loc['python']

name         F
marks       80
bonus       10
city     anand
total    90.92
Name: python, dtype: object

## iloc method

In [45]:
df.iloc[0]

name       A
marks    200
bonus      1
city     ahm
total    201
Name: 0, dtype: object

In [44]:
df.iloc[0:2]   # last index is not included here

  name  marks  bonus city  total
0    A  200.0      1  ahm  201.0
1    B   90.0      2  raj   92.0

In [46]:
df.iloc[0:2,'city']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [48]:
df.iloc[0:2,3]

0    ahm
1    raj
Name: city, dtype: object

In [54]:
df.iloc[8]

name         F
marks       80
bonus       10
city     anand
total    90.92
Name: python, dtype: object

In [50]:
df.loc['python']

name         F
marks       80
bonus       10
city     anand
total    90.92
Name: python, dtype: object

## Viewing data

## head()
- to view first 5 rows

In [55]:
df.head()

  name  marks  bonus city  total
0    A  200.0      1  ahm  201.0
1    B   90.0      2  raj   92.0
2    C   95.0      3  ahm   98.0
3    D    NaN      4  ahm    NaN
4    E   99.0      7  raj  106.0

## tail()
- to view last 5 rows

In [56]:
df.tail()

       name  marks  bonus   city   total
4         E   99.0      7    raj  106.00
6         F   80.0     10  anand   90.92
5         F   80.0     10  anand   90.92
500       F   80.0     10  anand   90.92
python    F   80.0     10  anand   90.92

## sample()
- to randomly view rows

In [57]:
df.sample(2)

  name  marks  bonus   city  total
2    C   95.0      3    ahm  98.00
5    F   80.0     10  anand  90.92

## inspect data

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to python
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    9 non-null      object
 1   marks   8 non-null      float64
 2   bonus   9 non-null      int64
 3   city    9 non-null      object
 4   total   8 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 752.0+ bytes

## describe method
- statistical summary

**syntax**
```python
df.describe(include=,exclude=,percentile=)
```

In [61]:
df.describe()

            marks      bonus       total
count    8.000000   9.000000    8.000000
mean   100.500000   6.333333  107.585000
std     40.925019   3.840573   38.124847
min     80.000000   1.000000   90.920000
25%     80.000000   3.000000   90.920000
50%     85.000000   7.000000   91.460000
75%     96.000000  10.000000  100.000000
max    200.000000  10.000000  201.000000

In [63]:
df.describe(include='all')

       name       marks      bonus   city       total
count     9    8.000000   9.000000      9    8.000000
unique    6         NaN        NaN      3         NaN
top       F         NaN        NaN  anand         NaN
freq      4         NaN        NaN      4         NaN
mean    NaN  100.500000   6.333333    NaN  107.585000
std     NaN   40.925019   3.840573    NaN   38.124847
min     NaN   80.000000   1.000000    NaN   90.920000
25%     NaN   80.000000   3.000000    NaN   90.920000
50%     NaN   85.000000   7.000000    NaN   91.460000
75%     NaN   96.000000  10.000000    NaN  100.000000
max     NaN  200.000000  10.000000    NaN  201.000000

In [65]:
df.describe(exclude='object').round(2)

        marks  bonus   total
count    8.00   9.00    8.00
mean   100.50   6.33  107.58
std     40.93   3.84   38.12
min     80.00   1.00   90.92
25%     80.00   3.00   90.92
50%     85.00   7.00   91.46
75%     96.00  10.00  100.00
max    200.00  10.00  201.00

In [68]:
df.describe(percentiles=[0.2,0.3,0.5,0.9]).round(2)

        marks  bonus   total
count    8.00   9.00    8.00
mean   100.50   6.33  107.58
std     40.93   3.84   38.12
min     80.00   1.00   90.92
20%     80.00   2.60   90.92
30%     80.00   3.40   90.92
50%     85.00   7.00   91.46
90%    129.30  10.00  134.50
max    200.00  10.00  201.00

In [69]:
mystatistics=df.describe(percentiles=[0.2,0.3,0.5,0.9]).round(2)
type(mystatistics)

pandas.core.frame.DataFrame

In [70]:
mystatistics['marks']

count      8.00
mean     100.50
std       40.93
min       80.00
20%       80.00
30%       80.00
50%       85.00
90%      129.30
max      200.00
Name: marks, dtype: float64

## unique and nunique method
- unique method
    - unique values
- nunique method
    - no. of unique values

In [71]:
df['city'].unique()

array(['ahm', 'raj', 'anand'], dtype=object)

In [72]:
df['city'].nunique()

3

## Value_counts
- counts the frequency

In [73]:
df['city'].value_counts()

anand    4
ahm      3
raj      2
Name: city, dtype: int64

In [74]:
df['city'].value_counts(ascending=True)

raj      2
ahm      3
anand    4
Name: city, dtype: int64